import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import localFont from "next/font/local";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});

export const metadata: Metadata = {
  title: "안녕하세요 Next App 입니다.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <header className="w-full h-[60px] flex justify-center items-center">
          <Image
            width={300}
            height={300}
            src={"/assets/logo2.png"}
            alt="logo"
          ></Image>
        </header>
        {children}
      </body>
    </html>
  );
}
