import Link from "next/link";

type Props = {
  params: {
    id: string;
  };
};
export const generageMetadata = ({ params }: Props) => {
  return {
    title: `안녕하세요 About Page입니다. ${params.id}`,
    description: "Generated by create next app",
  };
};

export default function AboutPage() {
  return (
    <>
      <Link href={"/about2"}>about2로 이동</Link>
    </>
  );
}
